"""Shared dataclasses and enums used across promptpilot."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class TaskType(str, Enum):
    BUG_FIX = "bug_fix"
    FEATURE_IMPLEMENTATION = "feature_implementation"
    REFACTOR = "refactor"
    PERFORMANCE = "performance"
    CODE_EXPLANATION = "code_explanation"
    ROOT_CAUSE_ANALYSIS = "root_cause_analysis"
    TEST_GENERATION = "test_generation"
    MIGRATION = "migration"
    ARCHITECTURE_DESIGN = "architecture_design"
    DOCUMENTATION = "documentation"
    UNKNOWN = "unknown"


class Confidence(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class RewriteMode(str, Enum):
    PASS_THROUGH = "pass_through"
    EXTRACT_ONLY = "extract_only"
    EXTRACT_PLUS_LIGHT_REWRITE = "extract_plus_light_rewrite"


@dataclass
class RepoMetadata:
    cwd: str
    branch: Optional[str] = None
    changed_files: List[str] = field(default_factory=list)
    diff: Optional[str] = None
    dominant_language: Optional[str] = None
    test_framework: Optional[str] = None


@dataclass
class NormalizedRequest:
    original_prompt: str
    task_type: str
    objective: str
    explicit_context: List[str]
    hard_constraints: List[str]
    soft_preferences: List[str]
    requested_output: List[str]
    protected_spans: List[str]
    ambiguities: List[str]
    assumptions: List[str]
    omissions: List[str]
    confidence: str
    needs_review: bool
    rewrite_mode: str
    normalized_prompt: str


@dataclass
class ValidationResult:
    semantic_preservation: str
    issues: List[str]
    recommended_action: str


@dataclass
class TokenStats:
    original_tokens: int              # tokens in the raw prompt (counted, not estimated)
    final_tokens: int                 # tokens in the final downstream prompt (counted)
    delta_tokens: int                 # original - final (positive = savings on input)
    haiku_input_tokens: int           # uncached input tokens consumed by the SLM
    haiku_output_tokens: int          # tokens generated by the SLM
    haiku_cost_usd: float             # cost of the SLM call (includes cache pricing)
    target_model: str                 # expensive model we're saving on
    gross_savings_usd: float          # delta_tokens * target input price
    net_savings_usd: float            # gross_savings - haiku_cost
    # Anthropic prompt-cache metrics (0 when caching not engaged)
    cache_read_input_tokens: int = 0       # cheap reads @ 0.10x
    cache_creation_input_tokens: int = 0   # writes @ 1.25x
    cache_savings_usd: float = 0.0         # counterfactual: what the read would have cost without cache
    # Populated only when --tool anthropic/openai is used (actual API call)
    actual_input_tokens: Optional[int] = None
    actual_output_tokens: Optional[int] = None
    actual_total_cost_usd: Optional[float] = None
